config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'welcome#index', as: 'root'
  
  get '/register', to: 'users#new'
  post '/users', to: 'users#create'

  get '/products', to: 'products#index'

  get '/profile', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/profile/edit', to: 'users#edit'
  patch '/profile', to: 'users#update'

  get '/user/password/edit', to: 'users_password#edit'
  patch '/user/password', to: 'users_password#update'

  get '/passwords/new', to: 'passwords#new'
  post '/passwords', to: 'passwords#create'
  get '/passwords/reset/:id', to: 'passwords#reset'
  patch '/passwords/:id', to: 'passwords#update'
  get '/passwords/edit/:id', to: 'passwords#edit'

  get '/reservation', to: 'reservations#index'
  get '/reservation/new', to: 'reservations#new'
  post '/reservation', to: 'reservations#create'
  delete '/reservation/:id', to: 'booking_products#destroy'

  namespace :admin do
    get '/bookings', to: 'bookings#index'

    resources :products, except: :show
    resources :users
    resources :posts, except: :show

    get '/users/:id/reservation/new', to: 'bookings#new'
    post '/users/:id/reservation', to: 'bookings#create'
    get '/users/:user_id/reservation/:booking_id/edit', to: 'bookings#edit'
    patch '/users/:user_id/reservation/:booking_id', to: 'bookings#update'
  end

  match '*path', to: 'static_pages#not_found', via: :all,  constraints: -> (req) { req.fullpath !~ /^\/rails\/active_storage\/blobs\/.*/ } 

end

app/views/partials/_admin_nav.html.erb
<div class="sidenav">
  <center>  
    <div class="hero-text-mobile-nav" >
      <a href="/" style="font-size: 30px;"> Les Filles d'Antoine <a>
    </div>    
  </center> 
  <center> <div style="width:50px;" > <%= image_tag "logo.png",:style => "width:35px" %> </div> </center> 
  <br><br>


  <table class="table" style="width: 60%">
  <tr>
    <th style="border: 0" class="align-middle" style="width: 2%">  </th>
    <th style="border: 0" class="align-middle" style="width: 93%">  </th>
    <th style="border: 0" class="align-middle" style="width: 10%">  </th>
  </tr>

  <tr>
    <td style="padding-left:40px; padding-right:0px;border-top: 0" class="align-middle"> <a href="/profile" ><i class="fa fa-user-circle-o" aria-hidden="true"></i></a></td>
    <td style="text-align:left;border-top: 0"> <a href="/profile" > Profil </a> </td>
    <td style="border-top: 0"> <a href="/profile" ><i class="fa fa-angle-right" aria-hidden="true"></i></a> </td>
  </tr>

  <tr>
    <td style="padding-left:40px; padding-right:0px;border-top: 0" class="align-middle"> <a href="/admin/users" ><i class="fa fa-users " aria-hidden="true"></i> </a> </td>
    <td style="text-align:left;border-top: 0" class="text-left"> <a href="/admin/users" >Clients</a> </td>
    <td style="border-top: 0" class="align-middle"> <a href="/admin/users" ><i class="fa fa-angle-right" aria-hidden="true"></i></a> </td>
  </tr>
  <tr>
    <td style="padding-left:40px; padding-right:0px;border-top: 0" class="align-middle"> <a href="/admin/bookings" ><i class="fa fa-calendar-check-o" aria-hidden="true"></i></a></td>
    <td style="text-align:left;border-top: 0" class="text-left"> <a href="/admin/bookings" >Réservations</a> </td>
    <td style="border-top: 0" class="align-middle"> <a href="/admin/bookings" ><i class="fa fa-angle-right" aria-hidden="true"></i></a> </td>
  </tr>
  <tr>
    <td style="padding-left:40px; padding-right:0px;border-top: 0" class="align-middle"> <a href="/admin/products" ><i class="fa fa-cubes" aria-hidden="true"></i></a></td>
    <td style="text-align:left;border-top: 0" class="text-left"> <a href="/admin/products" >Produits</a> </td>
    <td style="border-top: 0" class="align-middle"> <a href="/admin/products" ><i class="fa fa-angle-right" aria-hidden="true"></i></a> </td>
  </tr>
  <tr>
    <td style="padding-left:40px; padding-right:0px;border-top: 0" class="align-middle"> <a href="/admin/posts" ><i class="fa fa-newspaper-o" aria-hidden="true"></i></a></td>
    <td style="text-align:left;border-top: 0" class="text-left"> <a href="/admin/posts" >Posts</a> </td>
    <td style="border-top: 0" class="align-middle"> <a href="/admin/posts" ><i class="fa fa-angle-right" aria-hidden="true"></i></a> </td>
  </tr>
  <tr>
    <td style="padding-left:40px; padding-right:0px;border-top: 0" class="align-middle"> <a href="/logout" ><i class="fa fa-sign-out" aria-hidden="true"></i></a></td>
    <td style="text-align:left;border-top: 0" class="text-left"> <a href="/logout" >Déconnexion</a> </td>
    <td style="border-top: 0" class="align-middle">  </td>
  </tr>

  </table>

</div>

app/views/partials/_admin_user_body.html.erb
<body class="main_admin" >

  <% flash.each do |type, msg| %>
    <div class="alert alert-admin alert-<%=type%>">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= msg %>
    </div>
  <% end %>

  <%= yield %>

</body>

app/views/partials/_booking_button.html.erb
<div class="<%= browser_type %>-booking">
  <a class="btn btn-warning <%=browser_info.mobile? ? '' : 'btn-lg' %> link" href="/reservation/new">Réservez du miel</a>
</div>

app/views/partials/_booking_manual.html.erb
<div style="margin-left:<%=browser_info.mobile? ? '5px' : '10%' %>;width:<%=browser_info.mobile? ? "98%" : "550px" %>; text-align:justify;margin-right:200px" class="alert alert-success img-responsive" role="alert">
  
  <b> <i class="fa fa-forumbee" aria-hidden="true"></i> &nbsp;&nbsp; Pourquoi réserver ?</b>  <br>  <br>
  <i>Les réservations vous assurent que les pots de miel que vous souhaitez seront bien mis de côté pour vous après chaque récolte.</i> <br>  
  <hr>
  <b> <i class="fa fa-forumbee" aria-hidden="true"></i> &nbsp;&nbsp;J'ai réservé... et maintenant ? </b> <br>  <br>
  <i> Une fois la récolte du miel terminée, vous serez informé(e) par email et il ne vous restera plus qu'à venir le retirer en main propre.</i> <br> 
  <hr>
  <b> <i class="fa fa-forumbee" aria-hidden="true"></i> &nbsp;&nbsp;Quand les récoltes ont-elles lieu ? </b> <br>  <br>
  <i> La récolte de printemps a généralement lieu à la mi-mai et celle d'été à la fin du mois de juillet.</i> <br>  
  <hr>
  <b> <i class="fa fa-forumbee" aria-hidden="true"></i> &nbsp;&nbsp;Comment payer les pots réservés ? </b> <br>  <br>
  <i> Les réservations de pots ne nécessitent aucun prépaiement et le règlement se fait directement auprès d'Antoine au moment de leur réception. </i><br> 
  <hr>
  <b> <i class="fa fa-forumbee" aria-hidden="true"></i> &nbsp;&nbsp;Comment annuler ma réservation ? </b> <br>  <br>
  <i> Vous pouvez retirer des produits de vos réservations en cliquant sur le bouton 'Annuler' à la droite de chaque réservation. </i>
  
</div>

app/views/partials/_booking_product_form.html.erb
<% unless locals[:products].empty? %>
  <div>
    <table class="table table-hover table-sm" style="width: <%=browser_info.mobile? ? "100%" : "450px" %>">
      <thead class="thead-light">
        <tr>
          <th class="align-middle" style="width: <%=browser_info.mobile? ? '145px' : '50%'%>"> <%= locals[:title]%> <%= Time.new.year %> </th>
          <th class="align-middle" style="width: 30%"> Prix Unité </th>
          <th class="align-middle" style="width: 20%"> Quantité </th>
        </tr>
      </thead>
      <% locals[:products].each do |product| %>
        <tr id="product-<%= product.id %>">
          <td class="align-middle"><%= product.description %></td>
          <td class="align-middle"><%= "#{product.price} €" %> </td>
          <td class="align-middle"><%= locals[:form].number_field (product.description + '_' + product.season).to_sym, :value => locals[:booking][(product.description + '_' + product.season).to_sym], placeholder: '0', max: 100, min: 0, style:"width:40px" %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>
  

app/views/partials/_connexion_modal.html.erb
<div class="modal" id="connectModal" tabindex="-1" role="dialog" aria-labelledby="connectModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h5 class="modal-title w-100" id="connectModalLabel">Connectez-vous pour réserver...</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <div class="modal-footer justify-content-between" style='text-align:center'>
        
          <div style="padding-top:40px; padding-bottom:40px;">
            Je n'ai pas encore de compte <br><br>
            <a href="/register" class="btn btn-outline-primary" role="button" aria-pressed="true">Je m'inscris</a>
            <br><br>
            ~  OU  ~
            <br><br>
            J'ai déjà un compte <br><br>
            <a href="/login" class="btn btn-outline-primary" role="button" aria-pressed="true">Je me connecte</a>
            <br><br>
            <%= link_to "Mot de passe oublié ?", passwords_new_path%>            
          </div>
        
      </div>
    </div>
  </div>
</div>

app/views/partials/_current_user_mobile_nav.html.erb
<div id="mySidenav" class="sidenav_mobile">
    <center>  
    <div class="hero-text-mobile-nav" >
      Les Filles d'Antoine
    </div>    
  </center> 

  <table class="table" style="width: 100%">
  <tr>
    <th style="border: 0" class="align-middle" style="width: 2%">  </th>
    <th style="border: 0" class="align-middle" style="width: 93%">  </th>
    <th style="border: 0" class="align-middle" style="width: 5%">  </th>
  </tr>
  <tr  >
    <td style="border-top: 1px dashed #818181" class="align-middle"> <a href="/"onclick="closeNav()" ><i class="fa fa-home " aria-hidden="true"></i> </a> </td>
    <td style="border-top: 1px dashed #818181" class="text-left"> <a href="/"onclick="closeNav()" >Accueil</a> </td>
    <td style="border-top: 1px dashed #818181" class="align-middle"> <a href="/"onclick="closeNav()" ><i class="fa fa-angle-right" aria-hidden="true"></i></a> </td>
  </tr>
  <tr>
    <td style="border-top: 1px dashed #818181" class="align-middle"> <a href="/profile"onclick="closeNav()" ><i class="fa fa-user-circle-o" aria-hidden="true"></i></a></td>
    <td style="border-top: 1px dashed #818181" class="text-left"> <a href="/profile"onclick="closeNav()" > <%= current_user.first_name.capitalize %> </a> </td>
    <td style="border-top: 1px dashed #818181" class="align-middle"> <a href="/profile"onclick="closeNav()" ><i class="fa fa-angle-right" aria-hidden="true"></i></a> </td>
  </tr>
  <tr>
    <td style="border-top: 1px dashed #818181" class="align-middle"> <a href="/reservation"onclick="closeNav()" ><i class="fa fa-calendar" aria-hidden="true"></i></a></td>
    <td style="border-top: 1px dashed #818181" class="text-left"> <a href="/reservation"onclick="closeNav()" >Mes Réservations</a> </td>
    <td style="border-top: 1px dashed #818181" class="align-middle"> <a href="/reservation"onclick="closeNav()" ><i class="fa fa-angle-right" aria-hidden="true"></i></a> </td>
  </tr>
  <tr>
    <td style="border-top: 1px dashed #818181" class="align-middle"> <a href="/products"onclick="closeNav()" ><i class="fa fa-star-o" aria-hidden="true"></i></a></td>
    <td style="border-top: 1px dashed #818181" class="text-left"> <a href="/products"onclick="closeNav()" >Les Produits d'Antoine</a> </td>
    <td style="border-top: 1px dashed #818181" class="align-middle"> <a href="/products"onclick="closeNav()" ><i class="fa fa-angle-right" aria-hidden="true"></i></a> </td>
  </tr>


  <tr>
    <td style="border-top: 1px dashed #818181; border-bottom: 1px dashed #818181" class="align-middle"> <a href="/logout"onclick="closeNav()" ><i class="fa fa-sign-out" aria-hidden="true"></i></a></td>
    <td style="border-top: 1px dashed #818181; border-bottom: 1px dashed #818181" class="text-left"> <a href="/logout"onclick="closeNav()" >Déconnexion</a> </td>
    <td style="border-top: 1px dashed #818181; border-bottom: 1px dashed #818181" class="align-middle"> <a href="/logout"onclick="closeNav()" ><i class="fa fa-angle-right" aria-hidden="true"></i></a> </td>
  </tr>

  </table>
   <center>
    <div style="width:50px;" >
      <%= image_tag "logo.png",:style => "width:50px" %>
    </div>    
  </center> 

</div>

app/views/partials/_desktop_body.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%=type%> alert-fixed" >
    <a href="#" data-dismiss="alert" class="close">×</a>
    <%= msg %>
  </div>
<% end %>

<body id="main">
  <%= yield %>
</body>

app/views/partials/_footer.html.erb
<footer id="footer">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: #242829">
    © 2020 - 
    <a class="text-light" href="https://www.lesfillesdantoine.com/">© 2021 - LesFillesDAntoine.com</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/partials/_mobile_body.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%=type%> alert-fixed-mobile ">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <%= msg %>
  </div>
<% end %>

<body id="main">

  <div class="mobile-top-bar">
    <span class="reg-content-text top-menu-mobile" onclick="openNav()">&#9776; menu <span style= "padding-left:20%"> <%= image_tag "logo.png",:style => "width:35px" %> </span> </span>
  </div>
  
  <%= yield %>

</body>

app/views/partials/_post_form.html.erb
<center>

  <h3> <%= locals[:verb] %> le post </h3>
  <br>
  <%= form_with model: locals[:post], local: true, url: locals[:url], method: locals[:action] do |f| %>
    <p> <%= f.text_area :title, :value => locals[:post].title, :cols => "40", placeholder: ('Titre *' if locals[:action] == :post) %> </p>
    <p> <%= f.text_area :content, :value => locals[:post].content, :cols => "40", :rows => "10", placeholder: ('Contenu *' if locals[:action] == :post) %> </p>
    <p> <%= f.file_field :images, multiple: true %> </p> 
    <br>
    <%= f.submit "Continuer", class: "btn btn-primary" %>
 <% end %>

</center>

app/views/partials/_product_form.html.erb
<center>

  <h3> <%= locals[:verb] %> le produit </h3>
  <br>
  <%= form_with model: locals[:product], local: true, url: locals[:url], method: locals[:action] do |f| %>
    <p> <%= f.text_field :description, :value => locals[:product].description, placeholder: ('Description *' if locals[:action] == :post) %> </p>
    <p> <%= f.text_field :price, :value => locals[:product].price, placeholder: ('Prix *' if locals[:action] == :post) %> </p>
    <p> <%= f.text_field :year, :value => locals[:product].year,  placeholder: ('Année *' if locals[:action] == :post) %> </p>
    <table class="table" style="width:20%">
      <tr>
        <th class="align-middle" style="border: 0"> </th>
        <th class="align-middle" style="border: 0"> </th>
      </tr>
      <tr>
        <td class="align-middle" style="text-align:right; border-top: 0"> <%= f.label :season, 'printemps', :value => true  %> <%= f.radio_button :season, 'printemps', :checked => (locals[:product].season == 'printemps') %> </td>
        <td class="align-middle" style="text-align:right; border-top: 0"> <%= f.label :season, 'été', :value => false %> <%= f.radio_button :season, 'été', :checked => (locals[:product].season == 'été') %>  </td>
      </tr>
      <tr>
        <td class="align-middle" style="text-align:right; border-top: 0"> <%= f.label :status, 'actif', :value => true  %> <%= f.radio_button :status, 'active', :checked => (locals[:product].status == 'active') %> </td>
        <td class="align-middle" style="text-align:right; border-top: 0"> <%= f.label :status, 'inactif', :value => false %> <%= f.radio_button :status, 'inactive', :checked => (locals[:product].status == 'inactive') %> </td>
      </tr>
    </table>
    <%= f.submit "Continuer", class: "btn btn-primary" %>
 <% end %>

</center>
 

app/views/partials/_profile_table.html.erb
<table class="table" style="width:500px">
      <tr>
        <th class="align-middle" style="border: 0; width: 10px;"> </th>
        <th class="align-middle" style="border: 0; width: 450px;"> </th>
      </tr>
      <tr>
        <td class="align-middle" style="text-align:left; border-top: 0"> <i class="fa fa-address-card" aria-hidden="true"></i> </td>
        <td class="align-middle" style="text-align:left; border-top: 0"> <%=locals[:user].full_name %> </td>
      </tr>
      <tr>
        <td class="align-middle" style="text-align:left; border-top: 0"> <i class="fa fa-envelope-open-o" aria-hidden="true"> </td>
        <td class="align-middle" style="text-align:left; border-top: 0"> <%=locals[:user].email%> </td>
      </tr>
      <tr>
        <td class="align-middle" style="text-align:left; border-top: 0"> <i class="fa fa-phone" aria-hidden="true"></i> </td>
        <td class="align-middle" style="text-align:left; border-top: 0"> <%=locals[:user].phone_number%> </td>
      </tr>
      <tr>
        <td class="align-middle" style="text-align:left; border-top: 0"> <i class="fa fa-map-o" aria-hidden="true"></i> </td>
        <td class="align-middle" style="text-align:left; border-top: 0"> <%=locals[:user].full_address %> </td>
      </tr>

</table>

app/views/partials/_visitor_mobile_nav.html.erb
<div id="mySidenav" class="sidenav_mobile">

  <center>  
    <div class="hero-text-mobile-nav" >
      Les Filles d'Antoine
    </div>    
  </center> 

  <table class="table" style="width: 100%">
  <tr>
    <th style="border: 0" class="align-middle" style="width: 2%">  </th>
    <th style="border: 0" class="align-middle" style="width: 93%">  </th>
    <th style="border: 0" class="align-middle" style="width: 5%">  </th>
  </tr>
  <tr  >
    <td style="border-top: 1px dashed #818181" class="align-middle"> <a href="/"onclick="closeNav()" ><i class="fa fa-home " aria-hidden="true"></i> </a> </td>
    <td style="border-top: 1px dashed #818181" class="text-left"> <a href="/"onclick="closeNav()" >Accueil</a> </td>
    <td style="border-top: 1px dashed #818181" class="align-middle"> <a href="/"onclick="closeNav()" ><i class="fa fa-angle-right" aria-hidden="true"></i></a> </td>
  </tr>
  <tr>
    <td style="border-top: 1px dashed #818181" class="align-middle"> <a href="/products"onclick="closeNav()" ><i class="fa fa-star-o" aria-hidden="true"></i></a></td>
    <td style="border-top: 1px dashed #818181" class="text-left"> <a href="/products"onclick="closeNav()" >Les produits d'Antoine</a> </td>
    <td style="border-top: 1px dashed #818181" class="align-middle"> <a href="/products"onclick="closeNav()" ><i class="fa fa-angle-right" aria-hidden="true"></i></a> </td>
  </tr>
  <tr>
    <td style="border-top: 1px dashed #818181" class="align-middle link"><a> <i class="fa fa-calendar" aria-hidden="true"></i></a></td>
    <td style="border-top: 1px dashed #818181" class="text-left"> <a href="/reservation"onclick="closeNav()">Les Réservations </a> </td>
    <td style="border-top: 1px dashed #818181" class="align-middle link"> <a> <i class="fa fa-angle-right" aria-hidden="true"></i></a> </td>
  </tr>
  <tr>
    <td style="border-top: 1px dashed #818181; border-bottom: 1px dashed #818181" class="align-middle"> <a href="/login"onclick="closeNav()" ><i class="fa fa-sign-in" aria-hidden="true"></i></a></td>
    <td style="border-top: 1px dashed #818181; border-bottom: 1px dashed #818181" class="text-left"> <a href="/login"onclick="closeNav()" >Connexion</a> </td>
    <td style="border-top: 1px dashed #818181; border-bottom: 1px dashed #818181" class="align-middle"> <a href="/login"onclick="closeNav()" ><i class="fa fa-angle-right" aria-hidden="true"></i></a> </td>
  </tr>

  </table>

   <center>
    <div style="width:50px;" >
      <%= image_tag "logo.png",:style => "width:50px" %>
    </div>    
  </center> 

</div>

<div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h5 class="modal-title w-100" id="exampleModalLabel">Connectez-vous pour réserver...</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <div class="modal-footer justify-content-between" style='text-align:center'>
        
          <div style="padding-top:40px; padding-bottom:40px;">
            Je n'ai pas encore de compte <br><br>
            <a href="/register" class="btn btn-outline-primary" role="button" aria-pressed="true">Je m'inscris</a>
            <br><br>
            ~  OU  ~
            <br><br>
            J'ai déjà un compte <br><br>
            <a href="/login" class="btn btn-outline-primary" role="button" aria-pressed="true">Je me connecte</a>
            <br><br>
            <%= link_to "Mot de passe oublié ?", passwords_new_path%>
          </div>
      </div>
    </div>
  </div>
</div>